### PR TITLE
Track todos

### PR DESCRIPTION
**Pull request by bglusman**
@aribrenner we can also create a PR for this in gitcolony to compare but thought I'd start here... It's not quite ready to merge yet, but basics are working, feel free to play around or make suggestions!

### CODE REVIEW

**Comment by bglusman** [comment]
Resolves #43 when merged, and looks like gitcolony already picked this up automatically which is nice...

**Comment by bglusman** [comment]
Hmm, weird some rubies passed and some failed, have to look into...

Meanwhile, @aribrenner think we want to include a) line numbers, and/or b) git blame who committed that line so you have an idea who to talk to if considering it/want more info?  I think it'd be nice/not too hard, but maybe that's a refinement once this is working OK for first release.

**Comment by bglusman** [comment]
@ybur-yug wow that is weird! a bit worrying too!  Wonder if it's a bug or a feature? maybe because you're an owner vs collaborator, if that's a distinction here?

**Comment by ybur-yug** [comment]
@bglusman I believe it is actually intentional, but I find it quite confusing. IIRC I found an article from GH on it earlier but cant seem to find it right now.

**Comment by bglusman** [comment]
There's probably some code cleanup/tech debt here, but the API seems stable so let's call it good for now.

**Comment by bglusman** [comment]
OK, well, I merged this, tagged, released, and then it looked like there were errors installing and running on a real project outside the repo, and/or some conditions not tested where analysed_modules method was called on nil, so yanked release and killed the tag...  will investigate and fix, but in case anyone was tracking this and waiting for a release on merge.

**Pull request merged**
